name: Build and Push Docker Image for Rustdesk

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download hbbs
      run: |
        latest_url=$(curl -s https://api.github.com/repos/sctg-development/sctgdesk-server/releases/latest | grep browser_download_url | grep amd64 | grep hbbs | cut -d '"' -f 4)
        curl -L $latest_url -o hbbs
        chmod +x hbbs

    - name: Download hbbr
      run: |
        latest_url=$(curl -s https://api.github.com/repos/sctg-development/sctgdesk-server/releases/latest | grep browser_download_url | grep amd64 | grep hbbr | cut -d '"' -f 4)
        curl -L $latest_url -o hbbr
        chmod +x hbbr

    - name: Build and push Docker image
      run: |
        cat <<EOF > Dockerfile
        FROM scratch
        COPY hbbs /usr/bin/hbbs
        COPY hbbr /usr/bin/hbbr
        WORKDIR /root
        EOF
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/rustdesk:latest --push .
