name: Build and Push Docker Image for Rustdesk

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download hbbs and hbbr
      run: |
        apt update && apt install -y unzip jq
        echo "Fetching latest release URL"
        latest_url=$(curl -s https://api.github.com/repos/sctg-development/sctgdesk-server/releases/latest | jq -r '.assets[] | select(.name | test("amd64.*zip$")) | .browser_download_url')
        echo "Downloading Rustdesk from $latest_url"
        curl -L $latest_url -o rustdesk.zip
        unzip rustdesk.zip
        chmod +x hbbs hbbr
        pwd

    - name: Build and push Docker image
      run: |
        pwd
        ls -lah
        cat <<EOF > Dockerfile
        FROM busybox
        COPY hbbs /usr/bin/hbbs
        COPY hbbr /usr/bin/hbbr
        WORKDIR /root
        EOF
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/rustdesk:latest --push .
